on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: write
name: Build
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        targets: [esp32]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: esp-idf build
        uses: Fishwaldo/esp-idf-ci-action@v1.1
        with:
          esp_idf_version: latest
          target: ${{ matrix.targets }}
          path: "."
      - name: Rename artifact
        run: |
          ls -lah 
          cp ./build/advanced_https_ota.bin advanced_https_ota-${{ matrix.targets }}.bin
      - name: Archive Firmware Files
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.targets }}-firmware
          path: "*-${{ matrix.targets }}.bin"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Firmware Files
        uses: actions/download-artifact@v2
        with:
          path: release
      - name: Release Firmware
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: release/*/*.bin
          generateReleaseNotes: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install mustache (to update the date in build.sh)
        run: apk add ruby && gem install mustache
      - name: creates the wanted files in output_temp/ - example script
        run: sh ./build.sh
      - name: filters output_temp/ to output/ using rsync (to exclude main.epub in this example)
        run: apk add rsync && rsync -arv --exclude="/main.epub" output_temp/ output/
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: output/
          destination-github-username: ${{ secrets.USER_NAME }}
          destination-repository-name: "esp32_vault"
          user-email: ${{ secrets.USER_EMAIL }}
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
